version: "3"
services:

  livebook-dewet:
    image: livebook/livebook
    container_name: livebook-dewet
    environment:
      - VERSION=docker
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - LIVEBOOK_PASSWORD=${LIVEBOOK_DEWET_PASSWORD}
      - OFFICE_LIGHT_WEBHOOK_ID=${OFFICE_LIGHT_WEBHOOK_ID}
    ports:
      - 9998:8080
    volumes:
      - ./data-dewet:/data
    restart: unless-stopped

  livebook-eva:
    image: livebook/livebook
    container_name: livebook-eva
    environment:
      - VERSION=docker
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - LIVEBOOK_PASSWORD=${LIVEBOOK_EVA_PASSWORD}
      - EVA_LIGHT_WEBHOOK_ID=${EVA_LIGHT_WEBHOOK_ID}
    ports:
      - 9999:8080
    volumes:
      - ./data-eva:/data
    restart: unless-stopped

  livebook-public:
    image: livebook/livebook
    container_name: livebook-public
    environment:
      - VERSION=docker
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - LIVEBOOK_PASSWORD=${LIVEBOOK_PUBLIC_PASSWORD}
    ports:
      - ${PUBLIC_PORT}:8080
    volumes:
      - ./data-public:/data
    restart: unless-stopped

